# booking-service/Dockerfile.dev

FROM openjdk:17-jdk-slim

RUN echo "🔥 Используется Dockerfile.dev"

# Установка зависимостей
RUN apt-get update && apt-get install -y default-mysql-client netcat curl unzip

# Устанавливаем Liquibase
RUN mkdir -p /opt/liquibase && \
    curl -L https://github.com/liquibase/liquibase/releases/download/v4.26.0/liquibase-4.26.0.tar.gz \
    | tar -xz -C /opt/liquibase && \
    chmod +x /opt/liquibase/liquibase && \
    ln -s /opt/liquibase/liquibase /usr/local/bin/liquibase || echo "Проверь, есть ли файл liquibase"

# Проверка пути
RUN ls -l /opt/liquibase

WORKDIR /app

# Копируем Maven Wrapper и pom.xml
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Скачиваем зависимости (чтобы использовать кеш)
RUN ./mvnw dependency:go-offline

# Копируем весь проект
COPY . .

# Открываем порт
EXPOSE 8080

# Указываем dev-профиль при запуске
#CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]