# dev

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    enabled: true # приминение миграций при старте приложения

server:
  port: 9066

logging:
  level:
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
