spring:
  datasource:
    url: jdbc:mariadb://maria-db_dev:3306/bookings
    username: booking_user
    password: secure_password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml

server:
  port: 9066
